const productData = {
  women: [
    {
      id: 1,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_1.png",
      new_price: 50.0,
      old_price: 80.5,
    },
    {
      id: 2,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_2.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 3,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_3.png",
      new_price: 60.0,
      old_price: 100.5,
    },
    {
      id: 4,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_4.png",
      new_price: 100.0,
      old_price: 150.0,
    },
    {
      id: 5,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_5.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 6,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_6.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 7,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_7.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 8,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_8.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 9,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_9.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 10,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_10.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 11,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_11.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 12,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "./public/product_12.png",
      new_price: 85.0,
      old_price: 120.5,
    },
  ],
  men: [
    {
      id: 13,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_13.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 14,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_14.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 15,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_15.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 16,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_16.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 17,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_17.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 18,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_18.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 19,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_19.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 20,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_20.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 21,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_21.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 22,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_22.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 23,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_23.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 24,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "./public/product_24.png",
      new_price: 85.0,
      old_price: 120.5,
    },
  ],

  kid: [
    {
      id: 25,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_25.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 26,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_26.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 27,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_27.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 28,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_28.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 29,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_29.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 30,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_30.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 31,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_31.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 32,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_32.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 33,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_33.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 34,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_34.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 35,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_35.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 36,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_36.png",
      new_price: 85.0,
      old_price: 120.5,
    },
  ],
  newCollection: [
    {
      id: 12,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "women",
      image: "./public/product_12.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 35,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_35.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 14,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "men",
      image: "./public/product_14.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 8,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "women",
      image: "./public/product_8.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 15,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "men",
      image: "./public/product_15.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 2,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "women",
      image: "./public/product_2.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 17,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "men",
      image: "./public/product_17.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 28,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "./public/product_28.png",
      new_price: 85.0,
      old_price: 120.5,
    },
  ],
};

// const newCollection = [
//   {
//     id: 12,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: "./public/product_12.png",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 35,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: "./public/product_35.png",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 14,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: "./public/product_14.png",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 8,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: "./public/product_8.png",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 15,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: "./public/product_15.png",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 2,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: "./public/product_2.png",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 17,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: "./public/product_17.png",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 28,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: "./public/product_28.png",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
// ];

module.exports = productData;
